### ISSUE TITLE
TODO (migration related)

### ISSUE THREAD

**Issue by Andersson007** [ansible-collections/community.postgresql#14]
##### SUMMARY
Relates to migration from `community.general` to this repository (the order is not strict)

- [x] Move issues / prs
- [x] Move saslprep unit tests
- [x] Copy changelog related things
- [x] Copy fragments
- [x] Release 0.1.0
- [x] Add redirect
- [ ] ~~BOTMETA.yml: migrated_to~~ Nothing uses `migrated_to` so we can skip this - gundalow
- [x] Remove all extra stuff from tests
- [x] Look through the [checklist](https://github.com/ansible-collections/overview/blob/main/collection_requirements.rst)
- [x] Look through the [migration doc](https://docs.ansible.com/ansible/devel/dev_guide/developing_collections.html#migrating-ansible-content-to-a-different-collection)

**Comment by Andersson007** [comment]
Solved
